#!/bin/tcsh

#setenv CLASSPATH ${COUGAAR_INSTALL_PATH}/lib/securityservices.jar

setenv CLASSPATH ${COUGAAR_INSTALL_PATH}/sys/jdom.jar
setenv CLASSPATH ${CLASSPATH}:${COUGAAR_INSTALL_PATH}/sys/xerces.jar
setenv CLASSPATH ${CLASSPATH}:${COUGAAR_INSTALL_PATH}/sys/jce1_2-do.jar
setenv CLASSPATH ${CLASSPATH}:${COUGAAR_INSTALL_PATH}/sys/cryptix-jce-api.jar
setenv CLASSPATH ${CLASSPATH}:${COUGAAR_INSTALL_PATH}/sys/cryptix-jce-provider.jar

setenv CLASSPATH ${CLASSPATH}:${COUGAAR_INSTALL_PATH}/lib/core.jar
setenv CLASSPATH ${CLASSPATH}:../../../classes

mkdir small-135
mkdir prototypeSociety

#################################
# Prototype society configuration
java \
	-Dorg.cougaar.install.path=${COUGAAR_INSTALL_PATH} \
	org.cougaar.core.security.tools.PolicyGenerator  \
	small135.conf policy.conf BootPolicyTemplate.xml small-135/CryptoPolicy-

#################################
# Small 135 society configuration
java \
	-Dorg.cougaar.install.path=${COUGAAR_INSTALL_PATH} \
	org.cougaar.core.security.tools.PolicyGenerator  \
	prototypesociety.conf policy.conf BootPolicyTemplate.xml prototypeSociety/CryptoPolicy-
