#!/bin/tcsh

#setenv CLASSPATH ${COUGAAR_INSTALL_PATH}/lib/securityservices.jar

setenv CLASSPATH ${COUGAAR_INSTALL_PATH}/sys/jdom.jar
setenv CLASSPATH ${CLASSPATH}:${COUGAAR_INSTALL_PATH}/sys/xerces.jar
setenv CLASSPATH ${CLASSPATH}:${COUGAAR_INSTALL_PATH}/sys/jce1_2-do.jar
setenv CLASSPATH ${CLASSPATH}:${COUGAAR_INSTALL_PATH}/sys/cryptix-jce-api.jar
setenv CLASSPATH ${CLASSPATH}:${COUGAAR_INSTALL_PATH}/sys/cryptix-jce-provider.jar

setenv CLASSPATH ${CLASSPATH}:${COUGAAR_INSTALL_PATH}/lib/core.jar
setenv CLASSPATH ${CLASSPATH}:../../../classes

java \
	-Dorg.cougaar.install.path=${COUGAAR_INSTALL_PATH} \
	com.nai.security.tools.PolicyGenerator  \
	society.conf policy.conf BootPolicyTemplate.xml CryptoPolicy-
