#!/bin/sh

# <copyright>
#  Copyright 2001 BBNT Solutions, LLC
#  under sponsorship of the Defense Advanced Research Projects Agency (DARPA).
# 
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the Cougaar Open Source License as published by
#  DARPA on the Cougaar Open Source Website (www.cougaar.org).
# 
#  THE COUGAAR SOFTWARE AND ANY DERIVATIVE SUPPLIED BY LICENSOR IS
#  PROVIDED 'AS IS' WITHOUT WARRANTIES OF ANY KIND, WHETHER EXPRESS OR
#  IMPLIED, INCLUDING (BUT NOT LIMITED TO) ALL IMPLIED WARRANTIES OF
#  MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE, AND WITHOUT
#  ANY WARRANTIES AS TO NON-INFRINGEMENT.  IN NO EVENT SHALL COPYRIGHT
#  HOLDER BE LIABLE FOR ANY DIRECT, SPECIAL, INDIRECT OR CONSEQUENTIAL
#  DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE OF DATA OR PROFITS,
#  TORTIOUS CONDUCT, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
#  PERFORMANCE OF THE COUGAAR SOFTWARE.
# </copyright>

if [ "$COUGAAR_WORKSPACE" == "" ]; then
    COUGAAR_WORKSPACE=${COUGAAR_INSTALL_PATH}/bin
fi

source $COUGAAR_INSTALL_PATH/bin/setlibpath.sh
source $COUGAAR_INSTALL_PATH/bin/setarguments.sh

node="APP-AL-INVENTORY"
MYPROPERTIES="$MYPROPERTIES -Dorg.cougaar.security.role=${USER}"
MYPROPERTIES="$MYPROPERTIES -Dorg.cougaar.node.name=$node"
MYPROPERTIES="$MYPROPERTIES -Dorg.cougaar.config.path=.;${COUGAAR_INSTALL_PATH}/configs/security;"
MYPROPERTIES="$MYPROPERTIES -Dorg.cougaar.core.security.standalone=true"
MYPROPERTIES="$MYPROPERTIES -Dorg.cougaar.core.logging.log4j.appender.SECURITY.File=${node}.log"
MYPROPERTIES="$MYPROPERTIES -Dorg.cougaar.core.logging.config.filename=loggingConfig.conf"
MYPROPERTIES="$MYPROPERTIES -Dorg.cougaar.ui.userAuthClass=org.cougaar.core.security.userauth.UserAuthenticatorImpl"

MYCLASSES="org.cougaar.logistics.ui.inventory.InventoryUIFrame"

LIBPATHS="${LIBPATHS}:${COUGAAR_INSTALL_PATH}/lib/core.jar"
LIBPATHS="${LIBPATHS}:${COUGAAR_INSTALL_PATH}/lib/util.jar"
LIBPATHS="${LIBPATHS}:${COUGAAR_INSTALL_PATH}/lib/securebootstrapper.jar"
LIBPATHS="${LIBPATHS}:${COUGAAR_INSTALL_PATH}/lib/CougaarCRLextensions.jar"
LIBPATHS="${LIBPATHS}:${COUGAAR_INSTALL_PATH}/lib/securityservices.jar"
LIBPATHS="${LIBPATHS}:${COUGAAR_INSTALL_PATH}/sys/log4j.jar"
LIBPATHS="${LIBPATHS}:${COUGAAR_INSTALL_PATH}/sys/xerces.jar"
LIBPATHS="${LIBPATHS}:${COUGAAR_INSTALL_PATH}/sys/ibmpkcs.jar"
LIBPATHS="${LIBPATHS}:${COUGAAR_INSTALL_PATH}/sys/servlet.jar"

echo exec java $MYPROPERTIES -classpath $LIBPATHS $BOOTSTRAPPER $DEVP $MYCLASSES $*
exec java $MYPROPERTIES -classpath $LIBPATHS $BOOTSTRAPPER $DEVP $MYCLASSES $*
