#!/bin/bash
#  <copyright>
#   Copyright 2003 Cougaar Software, Inc.
#   under sponsorship of the Defense Advanced Research Projects Agency#   (DARPA).
# 
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the Cougaar Open Source License as published by
#   DARPA on the Cougaar Open Source Website (www.cougaar.org).
# 
#   THE COUGAAR SOFTWARE AND ANY DERIVATIVE SUPPLIED BY LICENSOR IS
#   PROVIDED 'AS IS' WITHOUT WARRANTIES OF ANY KIND, WHETHER EXPRESS OR
#   IMPLIED, INCLUDING (BUT NOT LIMITED TO) ALL IMPLIED WARRANTIES OF
#   MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE, AND WITHOUT
#   ANY WARRANTIES AS TO NON-INFRINGEMENT.  IN NO EVENT SHALL COPYRIGHT
#   HOLDER BE LIABLE FOR ANY DIRECT, SPECIAL, INDIRECT OR CONSEQUENTIAL
#   DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE OF DATA OR PROFITS,
#   TORTIOUS CONDUCT, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
#   PERFORMANCE OF THE COUGAAR SOFTWARE.
#  </copyright>


#
#  This script builds java constructs that map to the ontology names.  This means that
#  many naming mistakes will be caught by the compiler.
#


PKG=org.cougaar.core.security.policy.enforcers.ontology.jena

ProxiedOntologyJavaMapper \
      http://ontology.coginst.uwf.edu/Action.daml                    . ${PKG}

ProxiedOntologyJavaMapper \
     http://ontology.coginst.uwf.edu/Ultralog/Names/ActorClasses.daml      . ${PKG}

ProxiedOntologyJavaMapper \
      http://ontology.coginst.uwf.edu/Ultralog/Names/EntityInstances.daml  . ${PKG}

ProxiedOntologyJavaMapper \
      http://ontology.coginst.uwf.edu/Ultralog/UltralogAction.daml   . ${PKG}

ProxiedOntologyJavaMapper \
      http://ontology.coginst.uwf.edu/Ultralog/UltralogActor.daml    . ${PKG}

ProxiedOntologyJavaMapper \
      http://ontology.coginst.uwf.edu/Ultralog/UltralogEntity.daml   . ${PKG}
