#!/bin/tcsh -x
set user=isat
ldapdelete -x -r -D "cn=manager, dc=cougaar, dc=org" -w secret -h u034e "dc=${user}, dc=cougaar, dc=org"
ldapadd -x -D "cn=manager, dc=cougaar, dc=org" -f ${user}.ldif -w secret -h u034e
