#!/bin/tcsh
set user=srosset
ldapdelete -x -r -D "cn=manager, dc=cougaar, dc=org" -w secret -h pear "dc=${user}, dc=cougaar, dc=org"
ldapadd -x -D "cn=manager, dc=cougaar, dc=org" -f ${user}.ldif -w secret -h pear
