#!/bin/tcsh
set host=yew
ldapdelete -x -r -D "cn=manager, dc=cougaar, dc=org" -w secret -h ${host} "dc=${user}, dc=cougaar, dc=org"
ldapadd -x -D "cn=manager, dc=cougaar, dc=org" -f ${user}.ldif -w secret -h ${host}
