package org.cougaar.core.security.policy.enforcers.util;

import java.util.*;

public class SSLCipherSuites {
  public static final String SSL_RSA_WITH_NULL_MD5 =
    "SSL_RSA_WITH_NULL_MD5";
  public static final String SSL_RSA_WITH_NULL_SHA =
    "SSL_RSA_WITH_NULL_SHA";
  public static final String SSL_RSA_EXPORT_WITH_RC4_40_MD5 =
    "SSL_RSA_EXPORT_WITH_RC4_40_MD5";
  public static final String SSL_RSA_WITH_RC4_128_MD5 =
    "SSL_RSA_WITH_RC4_128_MD5";
  public static final String SSL_RSA_WITH_RC4_128_SHA =
    "SSL_RSA_WITH_RC4_128_SHA";
  public static final String SSL_RSA_EXPORT_WITH_RC2_CBC_40_MD5 =
    "SSL_RSA_EXPORT_WITH_RC2_CBC_40_MD5";
  public static final String SSL_RSA_WITH_IDEA_CBC_SHA =
    "SSL_RSA_WITH_IDEA_CBC_SHA";
  public static final String SSL_RSA_EXPORT_WITH_DES40_CBC_SHA =
    "SSL_RSA_EXPORT_WITH_DES40_CBC_SHA";
  public static final String SSL_RSA_WITH_DES_CBC_SHA =
    "SSL_RSA_WITH_DES_CBC_SHA";
  public static final String SSL_RSA_WITH_3DES_EDE_CBC_SHA =
    "SSL_RSA_WITH_3DES_EDE_CBC_SHA";

  public static final String SSL_DH_DSS_EXPORT_WITH_DES40_CBC_SHA =
    "SSL_DH_DSS_EXPORT_WITH_DES40_CBC_SHA";
  public static final String SSL_DH_DSS_WITH_DES_CBC_SHA =
    "SSL_DH_DSS_WITH_DES_CBC_SHA";
  public static final String SSL_DH_DSS_WITH_3DES_EDE_CBC_SHA =
    "SSL_DH_DSS_WITH_3DES_EDE_CBC_SHA";
  public static final String SSL_DH_RSA_EXPORT_WITH_DES40_CBC_SHA =
    "SSL_DH_RSA_EXPORT_WITH_DES40_CBC_SHA";
  public static final String SSL_DH_RSA_WITH_DES_CBC_SHA =
    "SSL_DH_RSA_WITH_DES_CBC_SHA";
  public static final String SSL_DH_RSA_WITH_3DES_EDE_CBC_SHA =
    "SSL_DH_RSA_WITH_3DES_EDE_CBC_SHA";
  public static final String SSL_DHE_DSS_EXPORT_WITH_DES40_CBC_SHA =
    "SSL_DHE_DSS_EXPORT_WITH_DES40_CBC_SHA";
  public static final String SSL_DHE_DSS_WITH_DES_CBC_SHA =
    "SSL_DHE_DSS_WITH_DES_CBC_SHA";
  public static final String SSL_DHE_DSS_WITH_3DES_EDE_CBC_SHA =
    "SSL_DHE_DSS_WITH_3DES_EDE_CBC_SHA";
  public static final String SSL_DHE_RSA_EXPORT_WITH_DES40_CBC_SHA =
    "SSL_DHE_RSA_EXPORT_WITH_DES40_CBC_SHA";
  public static final String SSL_DHE_RSA_WITH_DES_CBC_SHA =
    "SSL_DHE_RSA_WITH_DES_CBC_SHA";
  public static final String SSL_DHE_RSA_WITH_3DES_EDE_CBC_SHA =
    "SSL_DHE_RSA_WITH_3DES_EDE_CBC_SHA";

  public static final String SSL_DH_anon_EXPORT_WITH_RC4_40_MD5 =
    "SSL_DH_anon_EXPORT_WITH_RC4_40_MD5";
  public static final String SSL_DH_anon_WITH_RC4_128_MD5 =
    "SSL_DH_anon_WITH_RC4_128_MD5";
  public static final String SSL_DH_anon_EXPORT_WITH_DES40_CBC_SHA =
    "SSL_DH_anon_EXPORT_WITH_DES40_CBC_SHA";
  public static final String SSL_DH_anon_WITH_DES_CBC_SHA =
    "SSL_DH_anon_WITH_DES_CBC_SHA";
  public static final String SSL_DH_anon_WITH_3DES_EDE_CBC_SHA =
    "SSL_DH_anon_WITH_3DES_EDE_CBC_SHA";

  public static final String SSL_FORTEZZA_KEA_WITH_NULL_SHA =
    "SSL_FORTEZZA_KEA_WITH_NULL_SHA";
  public static final String SSL_FORTEZZA_KEA_WITH_FORTEZZA_CBC_SHA =
    "SSL_FORTEZZA_KEA_WITH_FORTEZZA_CBC_SHA";
  public static final String SSL_FORTEZZA_KEA_WITH_RC4_128_SHA =
    "SSL_FORTEZZA_KEA_WITH_RC4_128_SHA";

  // TLS v1.0 cipher suites.

  public static final String TLS_RSA_WITH_NULL_MD5 =
    "TLS_RSA_WITH_NULL_MD5";
  public static final String TLS_RSA_WITH_NULL_SHA =
    "TLS_RSA_WITH_NULL_SHA";
  public static final String TLS_RSA_EXPORT_WITH_RC4_40_MD5 =
    "TLS_RSA_EXPORT_WITH_RC4_40_MD5";
  public static final String TLS_RSA_WITH_RC4_128_MD5 =
    "TLS_RSA_WITH_RC4_128_MD5";
  public static final String TLS_RSA_WITH_RC4_128_SHA =
    "TLS_RSA_WITH_RC4_128_SHA";
  public static final String TLS_RSA_EXPORT_WITH_RC2_CBC_40_MD5 =
    "TLS_RSA_EXPORT_WITH_RC2_CBC_40_MD5";
  public static final String TLS_RSA_WITH_IDEA_CBC_SHA =
    "TLS_RSA_WITH_IDEA_CBC_SHA";
  public static final String TLS_RSA_EXPORT_WITH_DES40_CBC_SHA =
    "TLS_RSA_EXPORT_WITH_DES40_CBC_SHA";
  public static final String TLS_RSA_WITH_DES_CBC_SHA =
    "TLS_RSA_WITH_DES_CBC_SHA";
  public static final String TLS_RSA_WITH_3DES_EDE_CBC_SHA =
    "TLS_RSA_WITH_3DES_EDE_CBC_SHA";

  public static final String TLS_DH_DSS_EXPORT_WITH_DES40_CBC_SHA =
    "TLS_DH_DSS_EXPORT_WITH_DES40_CBC_SHA";
  public static final String TLS_DH_DSS_WITH_DES_CBC_SHA =
    "TLS_DH_DSS_WITH_DES_CBC_SHA";
  public static final String TLS_DH_DSS_WITH_3DES_EDE_CBC_SHA =
    "TLS_DH_DSS_WITH_3DES_EDE_CBC_SHA";
  public static final String TLS_DH_RSA_EXPORT_WITH_DES40_CBC_SHA =
    "TLS_DH_RSA_EXPORT_WITH_DES40_CBC_SHA";
  public static final String TLS_DH_RSA_WITH_DES_CBC_SHA =
    "TLS_DH_RSA_WITH_DES_CBC_SHA";
  public static final String TLS_DH_RSA_WITH_3DES_EDE_CBC_SHA =
    "TLS_DH_RSA_WITH_3DES_EDE_CBC_SHA";
  public static final String TLS_DHE_DSS_EXPORT_WITH_DES40_CBC_SHA =
    "TLS_DHE_DSS_EXPORT_WITH_DES40_CBC_SHA";
  public static final String TLS_DHE_DSS_WITH_DES_CBC_SHA =
    "TLS_DHE_DSS_WITH_DES_CBC_SHA";
  public static final String TLS_DHE_DSS_WITH_3DES_EDE_CBC_SHA =
    "TLS_DHE_DSS_WITH_3DES_EDE_CBC_SHA";
  public static final String TLS_DHE_RSA_EXPORT_WITH_DES40_CBC_SHA =
    "TLS_DHE_RSA_EXPORT_WITH_DES40_CBC_SHA";
  public static final String TLS_DHE_RSA_WITH_DES_CBC_SHA =
    "TLS_DHE_RSA_WITH_DES_CBC_SHA";
  public static final String TLS_DHE_RSA_WITH_3DES_EDE_CBC_SHA =
    "TLS_DHE_RSA_WITH_3DES_EDE_CBC_SHA";

  public static final String TLS_DH_anon_EXPORT_WITH_RC4_40_MD5 =
    "TLS_DH_anon_EXPORT_WITH_RC4_40_MD5";
  public static final String TLS_DH_anon_WITH_RC4_128_MD5 =
    "TLS_DH_anon_WITH_RC4_128_MD5";
  public static final String TLS_DH_anon_EXPORT_WITH_DES40_CBC_SHA =
    "TLS_DH_anon_EXPORT_WITH_DES40_CBC_SHA";
  public static final String TLS_DH_anon_WITH_DES_CBC_SHA =
    "TLS_DH_anon_WITH_DES_CBC_SHA";
  public static final String TLS_DH_anon_WITH_3DES_EDE_CBC_SHA =
    "TLS_DH_anon_WITH_3DES_EDE_CBC_SHA";

  // Additional Export 1024 and other cipher suites
  // Note: these ciphers can also be used in SSL v3.

  public static final String TLS_RSA_EXPORT1024_WITH_DES_CBC_SHA =
    "TLS_RSA_EXPORT1024_WITH_DES_CBC_SHA";
  public static final String TLS_RSA_EXPORT1024_WITH_RC4_56_SHA =
    "TLS_RSA_EXPORT1024_WITH_RC4_56_SHA";
  public static final String TLS_DHE_DSS_EXPORT1024_WITH_DES_CBC_SHA =
    "TLS_DHE_DSS_EXPORT1024_WITH_DES_CBC_SHA";
  public static final String TLS_DHE_DSS_EXPORT1024_WITH_RC4_56_SHA =
    "TLS_DHE_DSS_EXPORT1024_WITH_RC4_56_SHA";
  public static final String TLS_DHE_DSS_WITH_RC4_128_SHA =
    "TLS_DHE_DSS_WITH_RC4_128_SHA";

  // SSL v2.0 cipher suites.

  public static final String SSL_CK_RC4_128_WITH_MD5 =
    "SSL_CK_RC4_128_WITH_MD5";
  public static final String SSL_CK_RC4_128_EXPORT40_WITH_MD5 =
    "SSL_CK_RC4_128_EXPORT40_WITH_MD5";
  public static final String SSL_CK_RC2_128_CBC_WITH_MD5 =
    "SSL_CK_RC2_128_CBC_WITH_MD5";
  public static final String SSL_CK_RC2_128_CBC_EXPORT40_WITH_MD5 =
    "SSL_CK_RC2_128_CBC_EXPORT40_WITH_MD5";
  public static final String SSL_CK_IDEA_128_CBC_WITH_MD5 =
    "SSL_CK_IDEA_128_CBC_WITH_MD5";
  public static final String SSL_CK_DES_64_CBC_WITH_MD5 =
    "SSL_CK_DES_64_CBC_WITH_MD5";
  public static final String SSL_CK_DES_192_EDE3_CBC_WITH_MD5 =
    "SSL_CK_DES_192_EDE3_CBC_WITH_MD5";

  private static final Set _weak   = new HashSet();
  private static final Set _strong = new HashSet();
  private static final Set _all    = new HashSet();
  public static final Set WEAK_SUITES   = Collections.unmodifiableSet(_weak);
  public static final Set STRONG_SUITES = Collections.unmodifiableSet(_strong);
  public static final Set ALL_SUITES    = Collections.unmodifiableSet(_all);

  public static final String[] WEAK = {
    SSL_RSA_WITH_NULL_MD5,
    SSL_RSA_WITH_NULL_SHA,
    SSL_RSA_EXPORT_WITH_RC4_40_MD5,
    SSL_RSA_EXPORT_WITH_RC2_CBC_40_MD5,
    SSL_RSA_EXPORT_WITH_DES40_CBC_SHA,
    SSL_RSA_WITH_DES_CBC_SHA,
    SSL_DH_DSS_EXPORT_WITH_DES40_CBC_SHA,
    SSL_DH_DSS_WITH_DES_CBC_SHA,
    SSL_DH_RSA_EXPORT_WITH_DES40_CBC_SHA,
    SSL_DH_RSA_WITH_DES_CBC_SHA,
    SSL_DHE_DSS_EXPORT_WITH_DES40_CBC_SHA,
    SSL_DHE_DSS_WITH_DES_CBC_SHA,
    SSL_DHE_RSA_EXPORT_WITH_DES40_CBC_SHA,
    SSL_DHE_RSA_WITH_DES_CBC_SHA,
    SSL_DH_anon_EXPORT_WITH_RC4_40_MD5,
    SSL_DH_anon_EXPORT_WITH_DES40_CBC_SHA,
    SSL_DH_anon_WITH_DES_CBC_SHA,
    SSL_FORTEZZA_KEA_WITH_NULL_SHA,
    TLS_RSA_WITH_NULL_MD5,
    TLS_RSA_WITH_NULL_SHA,
    TLS_RSA_EXPORT_WITH_RC4_40_MD5,
    TLS_RSA_EXPORT_WITH_RC2_CBC_40_MD5,
    TLS_RSA_EXPORT_WITH_DES40_CBC_SHA,
    TLS_RSA_WITH_DES_CBC_SHA,
    TLS_DH_DSS_EXPORT_WITH_DES40_CBC_SHA,
    TLS_DH_DSS_WITH_DES_CBC_SHA,
    TLS_DH_RSA_EXPORT_WITH_DES40_CBC_SHA,
    TLS_DH_RSA_WITH_DES_CBC_SHA,
    TLS_DHE_DSS_EXPORT_WITH_DES40_CBC_SHA,
    TLS_DHE_DSS_WITH_DES_CBC_SHA,
    TLS_DHE_RSA_EXPORT_WITH_DES40_CBC_SHA,
    TLS_DHE_RSA_WITH_DES_CBC_SHA,
    TLS_DH_anon_EXPORT_WITH_RC4_40_MD5,
    TLS_DH_anon_EXPORT_WITH_DES40_CBC_SHA,
    TLS_DH_anon_WITH_DES_CBC_SHA,
    TLS_RSA_EXPORT1024_WITH_DES_CBC_SHA,
    TLS_RSA_EXPORT1024_WITH_RC4_56_SHA,
    TLS_DHE_DSS_EXPORT1024_WITH_DES_CBC_SHA,
    TLS_DHE_DSS_EXPORT1024_WITH_RC4_56_SHA,
    SSL_CK_RC4_128_EXPORT40_WITH_MD5,
    SSL_CK_RC2_128_CBC_EXPORT40_WITH_MD5,
    SSL_CK_DES_64_CBC_WITH_MD5
  };

  public static final String[] STRONG = {
    // someone should check these, please!!!
    SSL_RSA_WITH_RC4_128_MD5,
    SSL_RSA_WITH_RC4_128_SHA,
    SSL_RSA_WITH_IDEA_CBC_SHA, // don't know IDEA
    SSL_RSA_WITH_3DES_EDE_CBC_SHA,
    SSL_DH_DSS_WITH_3DES_EDE_CBC_SHA,
    SSL_DH_RSA_WITH_3DES_EDE_CBC_SHA,
    SSL_DHE_DSS_WITH_3DES_EDE_CBC_SHA, // don't know DHE_DSS
    SSL_DHE_RSA_WITH_3DES_EDE_CBC_SHA,
    SSL_DH_anon_WITH_RC4_128_MD5,
    SSL_DH_anon_WITH_3DES_EDE_CBC_SHA,
    SSL_FORTEZZA_KEA_WITH_FORTEZZA_CBC_SHA, // don't know FORTEZZA
    SSL_FORTEZZA_KEA_WITH_RC4_128_SHA,
    TLS_RSA_WITH_RC4_128_MD5,
    TLS_RSA_WITH_RC4_128_SHA,
    TLS_RSA_WITH_IDEA_CBC_SHA, // don't know IDEA
    TLS_RSA_WITH_3DES_EDE_CBC_SHA,
    TLS_DH_DSS_WITH_3DES_EDE_CBC_SHA,
    TLS_DH_RSA_WITH_3DES_EDE_CBC_SHA,
    TLS_DHE_DSS_WITH_3DES_EDE_CBC_SHA, // don't know DHE_DSS
    TLS_DHE_RSA_WITH_3DES_EDE_CBC_SHA,
    TLS_DH_anon_WITH_RC4_128_MD5,
    TLS_DH_anon_WITH_3DES_EDE_CBC_SHA,
    TLS_DHE_DSS_WITH_RC4_128_SHA, // don't know DHE_DSS
    SSL_CK_RC4_128_WITH_MD5,
    SSL_CK_RC2_128_CBC_WITH_MD5,
    SSL_CK_IDEA_128_CBC_WITH_MD5,
    SSL_CK_DES_192_EDE3_CBC_WITH_MD5
  };

  public static final String[] ALL = {
    SSL_RSA_WITH_NULL_MD5,
    SSL_RSA_WITH_NULL_SHA,
    SSL_RSA_EXPORT_WITH_RC4_40_MD5,
    SSL_RSA_WITH_RC4_128_MD5,
    SSL_RSA_WITH_RC4_128_SHA,
    SSL_RSA_EXPORT_WITH_RC2_CBC_40_MD5,
    SSL_RSA_WITH_IDEA_CBC_SHA,
    SSL_RSA_EXPORT_WITH_DES40_CBC_SHA,
    SSL_RSA_WITH_DES_CBC_SHA,
    SSL_RSA_WITH_3DES_EDE_CBC_SHA,
    SSL_DH_DSS_EXPORT_WITH_DES40_CBC_SHA,
    SSL_DH_DSS_WITH_DES_CBC_SHA,
    SSL_DH_DSS_WITH_3DES_EDE_CBC_SHA,
    SSL_DH_RSA_EXPORT_WITH_DES40_CBC_SHA,
    SSL_DH_RSA_WITH_DES_CBC_SHA,
    SSL_DH_RSA_WITH_3DES_EDE_CBC_SHA,
    SSL_DHE_DSS_EXPORT_WITH_DES40_CBC_SHA,
    SSL_DHE_DSS_WITH_DES_CBC_SHA,
    SSL_DHE_DSS_WITH_3DES_EDE_CBC_SHA,
    SSL_DHE_RSA_EXPORT_WITH_DES40_CBC_SHA,
    SSL_DHE_RSA_WITH_DES_CBC_SHA,
    SSL_DHE_RSA_WITH_3DES_EDE_CBC_SHA,
    SSL_DH_anon_EXPORT_WITH_RC4_40_MD5,
    SSL_DH_anon_WITH_RC4_128_MD5,
    SSL_DH_anon_EXPORT_WITH_DES40_CBC_SHA,
    SSL_DH_anon_WITH_DES_CBC_SHA,
    SSL_DH_anon_WITH_3DES_EDE_CBC_SHA,
    SSL_FORTEZZA_KEA_WITH_NULL_SHA,
    SSL_FORTEZZA_KEA_WITH_FORTEZZA_CBC_SHA,
    SSL_FORTEZZA_KEA_WITH_RC4_128_SHA,
    TLS_RSA_WITH_NULL_MD5,
    TLS_RSA_WITH_NULL_SHA,
    TLS_RSA_EXPORT_WITH_RC4_40_MD5,
    TLS_RSA_WITH_RC4_128_MD5,
    TLS_RSA_WITH_RC4_128_SHA,
    TLS_RSA_EXPORT_WITH_RC2_CBC_40_MD5,
    TLS_RSA_WITH_IDEA_CBC_SHA,
    TLS_RSA_EXPORT_WITH_DES40_CBC_SHA,
    TLS_RSA_WITH_DES_CBC_SHA,
    TLS_RSA_WITH_3DES_EDE_CBC_SHA,
    TLS_DH_DSS_EXPORT_WITH_DES40_CBC_SHA,
    TLS_DH_DSS_WITH_DES_CBC_SHA,
    TLS_DH_DSS_WITH_3DES_EDE_CBC_SHA,
    TLS_DH_RSA_EXPORT_WITH_DES40_CBC_SHA,
    TLS_DH_RSA_WITH_DES_CBC_SHA,
    TLS_DH_RSA_WITH_3DES_EDE_CBC_SHA,
    TLS_DHE_DSS_EXPORT_WITH_DES40_CBC_SHA,
    TLS_DHE_DSS_WITH_DES_CBC_SHA,
    TLS_DHE_DSS_WITH_3DES_EDE_CBC_SHA,
    TLS_DHE_RSA_EXPORT_WITH_DES40_CBC_SHA,
    TLS_DHE_RSA_WITH_DES_CBC_SHA,
    TLS_DHE_RSA_WITH_3DES_EDE_CBC_SHA,
    TLS_DH_anon_EXPORT_WITH_RC4_40_MD5,
    TLS_DH_anon_WITH_RC4_128_MD5,
    TLS_DH_anon_EXPORT_WITH_DES40_CBC_SHA,
    TLS_DH_anon_WITH_DES_CBC_SHA,
    TLS_DH_anon_WITH_3DES_EDE_CBC_SHA,
    TLS_RSA_EXPORT1024_WITH_DES_CBC_SHA,
    TLS_RSA_EXPORT1024_WITH_RC4_56_SHA,
    TLS_DHE_DSS_EXPORT1024_WITH_DES_CBC_SHA,
    TLS_DHE_DSS_EXPORT1024_WITH_RC4_56_SHA,
    TLS_DHE_DSS_WITH_RC4_128_SHA,
    SSL_CK_RC4_128_WITH_MD5,
    SSL_CK_RC4_128_EXPORT40_WITH_MD5,
    SSL_CK_RC2_128_CBC_WITH_MD5,
    SSL_CK_RC2_128_CBC_EXPORT40_WITH_MD5,
    SSL_CK_IDEA_128_CBC_WITH_MD5,
    SSL_CK_DES_64_CBC_WITH_MD5,
    SSL_CK_DES_192_EDE3_CBC_WITH_MD5
  };
  
  static {
    _weak.addAll(Arrays.asList(WEAK));
    _strong.addAll(Arrays.asList(STRONG));
    _all.addAll(Arrays.asList(ALL));
  }
}
