#!/bin/tcsh

# $1 : hostname
# $2 : directory
# $3 : node .ini file
# $4 : Additional commands to execute

#killall -w -KILL java

set directory = $2
set configfile = $3
set logfile = ~/demo/$1-$3.log
echo "Configuration file: " ${directory}/${configfile}
echo "Logging output to:  " ${logfile}

if ( $# > 3 ) then
	set script = ~/demo/$4
	echo "Script:  " ${script}
	cat ${script}
	source ${script}
endif

if ($?COUGAAR_USE_PERSISTENCE) then
	echo PERSISTENCE= $COUGAAR_USE_PERSISTENCE
endif

echo cd $directory
cd $directory
echo "$COUGAAR_INSTALL_PATH/bin/Node ${configfile} >& ${logfile}"
$COUGAAR_INSTALL_PATH/bin/Node ${configfile} >& ${logfile}

