#!/bin/tcsh

# $1 : hostname
# $2 : configuration directory
# $3 : node .ini file
# $4 : Name of file that contains additional commands to execute
# $5 : directory where $4 file is located

#killall -w -KILL java

set confdirectory = $2
set configfile = $3
set logfile = $5/$1-$3.log
echo "Configuration file: " ${confdirectory}/${configfile}
echo "Logging output to:  " ${logfile}

if ( $# > 3 ) then
	set script = $5/$4
	echo "Script:  " ${script}
	cat ${script}
	source ${script}
endif

if ($?COUGAAR_USE_PERSISTENCE) then
	echo PERSISTENCE= $COUGAAR_USE_PERSISTENCE
endif

echo cd $confdirectory
cd $confdirectory
echo "$COUGAAR_SECURITY_SERVICES/test/bin/SecureNode ${configfile} >& ${logfile}"
$COUGAAR_SECURITY_SERVICES/test/bin/SecureNode ${configfile} >& ${logfile}
#$COUGAAR_INSTALL_PATH/bin/Node ${configfile} >& ${logfile}

