#!/bin/bash


echo Remember to load set-kaos-vars!
for i in ${KAOS_ROOT}/lib/*.jar
do
   CLASSPATH=${CLASSPATH}:$i
done
export CLASSPATH

java -Xmx200m -Xss1024k -Xms100m kaos.tools.ontologyJavaMapper.OntologyJavaMapper http://ontology.coginst.uwf.edu/Ultralog/UltralogAction.daml .  dummy.ontology
java -Xmx200m -Xss1024k -Xms100m kaos.tools.ontologyJavaMapper.OntologyJavaMapper http://ontology.coginst.uwf.edu/Ultralog/Names/EntityInstances.daml .  dummy.ontology
java -Xmx200m -Xss1024k -Xms100m kaos.tools.ontologyJavaMapper.OntologyJavaMapper http://ontology.coginst.uwf.edu/Ultralog/Names/ActorClasses.daml .  dummy.ontology
