#!/bin/tcsh

#Remove unecessary files
find . -name '*~' -exec rm -rf {} \;
find . -name '.#*' -exec rm -rf {} \;
rm -rf classes/*
rm -rf test/doc/API/

# Java files
find src -name '*.java' -exec sarep 'com.nai.security.bootstrap' 'org.cougaar.core.security.securebootstrap' {} \;
find src -name '*.java' -exec sarep 'com.nai.security' 'org.cougaar.core.security' {} \;

# Configuration files
find test -exec sarep 'com.nai.security.bootstrap' 'org.cougaar.core.security.securebootstrap' {} \;
find test -exec sarep 'com.nai.security' 'org.cougaar.core.security' {} \;

# Makefiles
find . -name 'Makefile*' -exec sarep 'com.nai.security.bootstrap' 'org.cougaar.core.security.securebootstrap' {} \;
find . -name 'Makefile*' -exec sarep 'com.nai.security' 'org.cougaar.core.security' {} \;

echo  ############################################
# Remove 'CVS' directory under src/com
find src/com/ -name CVS -type d -exec rmdir {} \;

# Move bootstrap directory to securebootstrap
mv src/com/nai/security/bootstrap/ src/org/cougaar/core/security/securebootstrap

# Move com directory to org directory
mv src/com/nai/security src/org/cougaar/core

# Remove any remaining directory under com
rm -rf src/com
