#!/bin/tcsh

#Remove unecessary files
echo ' ++++++ Removing unecessary files'
find . -name '*~' -exec rm -rf {} \;
find . -name '.#*' -exec rm -rf {} \;
rm -rf classes/*
rm -rf test/doc/API/

echo ' ++++++ Search and replace com.nai -> org/cougaar'
# Files to modify:
#  - Java files
#  - Configuration files
#  - Makefiles
find src test ./Makefile* -exec sarep -m 'com.nai.security.bootstrap' 'org.cougaar.core.security.securebootstrap' {} \;
find src test ./Makefile* -exec sarep -m 'com.nai.security.monitoring' 'org.cougaar.core.security.oldmonitoring' {} \;
find src test ./Makefile* -exec sarep -m 'com.nai.security' 'org.cougaar.core.security' {} \;

find src test ./Makefile* -exec sarep 'com/nai/security/bootstrap' 'org/cougaar/core/security/securebootstrap' {} \;
find src test ./Makefile* -exec sarep 'com/nai/security/monitoring' 'org/cougaar/core/security/oldmonitoring' {} \;
find src test ./Makefile* -exec sarep 'com/nai/security' 'org/cougaar/core/security' {} \;

echo '############################################'
echo ' ++++++ Moving com directory to org/cougaar'
# Remove 'CVS' directory under src/com
find src/com/ -depth -name CVS -type d -exec rm -rf {} \;
find src/org/cougaar/core/security/securebootstrap/ -depth -name CVS -type d -exec rm -rf {} \;

# Move bootstrap directory to securebootstrap
mv src/com/nai/security/bootstrap/ src/org/cougaar/core/security/securebootstrap

# Move monitoring directory to oldmonitoring
mv src/com/nai/security/monitoring/ src/org/cougaar/core/security/oldmonitoring

# Move com directory to org directory
mv -f src/com/nai/security/* src/org/cougaar/core/security

# Remove any remaining directory under com
rm -rf src/com

# Remove '.sarep filesA
find . -name '*.sarep' -exec rm -f {} \;

echo ' ++++++ Done'
echo '############################################'
