#!/bin/sh

# Script to run snort.  Run as root.  Requires no args.

# Where all snort output goes
# Must be writable by root (not NFS)
logdir=/var/tmp/tcplogs

scriptdir=`dirname $0`

rm -rf $logdir
mkdir $logdir

echo "snort started"
nohup $scriptdir/runsnort-aux $logdir &> $logdir/snort.log &
